package com.internetbanking.desing;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AutorechargeDesign extends GridLayout {
	protected VerticalLayout mainLayout;
	protected ComboBox cbCardIn;
	protected CheckBox cbTime;
	protected VerticalLayout timeBlock;
	protected TextField tfPeriodTime;
	protected PopupDateField tfPeriodSinceDate;
	protected PopupDateField tfPeriodToDate;
	protected TextField tfPeriodRechargeSummRub;
	protected TextField tfPeriodRechargeSummCop;
	protected CheckBox cbAmount;
	protected VerticalLayout amountBlock;
	protected PopupDateField tfAmountSinceDate;
	protected PopupDateField tfAmountToDate;
	protected TextField tfAmountSummRub;
	protected TextField tfAmountSummCop;
	protected TextField tfAmountRechargeSummRub;
	protected TextField tfAmountRechargeSummCop;
	protected Button bConfirm;

	public AutorechargeDesign() {
		Design.read(this);
	}
}
