package com.internetbanking.desing;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CardsPageDesign extends GridLayout {
	protected HorizontalLayout mainLayout;
	protected Table table;
	protected Button bAddCard;
	protected TextField tfType;
	protected TextField tfName;
	protected Button bNameChange;
	protected HorizontalLayout changeNameBlock;
	protected Button bNameCancel;
	protected Button bNameConfirm;
	protected TextField tfNumber;
	protected TextField tfSummRub;
	protected TextField tfSummCop;
	protected Button bSetMainCard;
	protected Button bDeleteCard;

	public CardsPageDesign() {
		Design.read(this);
	}
}
