package com.internetbanking.desing;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MakeTransactionPageDesign extends HorizontalLayout {
	protected VerticalLayout mainLoyout;
	protected OptionGroup transactionType;
	protected ComboBox cbCardOut;
	protected VerticalLayout extendCard;
	protected TextField tfCardIn;
	protected VerticalLayout ourCard;
	protected ComboBox cbCardIn;
	protected TextField tfRub;
	protected TextField tfCop;
	protected Button bMakeTransactoin;

	public MakeTransactionPageDesign() {
		Design.read(this);
	}
}
