package com.internetbanking.desing;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RegistryPageDesign extends GridLayout {
	protected VerticalLayout mainLayout;
	protected TextField tfLogin;
	protected TextField tfCardNumber;
	protected TextField tfFirstName;
	protected TextField tfLastName;
	protected PasswordField tfPassword;
	protected PasswordField tfConfirmPassword;
	protected PasswordField tfConfirmCode;
	protected Button bSendCode;
	protected Button bCancel;
	protected Button bRegistry;

	public RegistryPageDesign() {
		Design.read(this);
	}
}
