package com.visual.window;

import com.Constants;
import com.enums.PlayerColor;
import com.enums.RaceType;
import com.interfaces.IKeyListener;
import com.interfaces.drawing.IDrawing;
import com.objects.Planet;
import com.objects.Race;
import com.objects.Space;

import java.util.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author до??
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private IDrawing drawing;
    private IKeyListener keyListener;

    public MainForm(IDrawing drawing, final IKeyListener keyListener) {
        initComponents();
        setDrawing(drawing);
        setKeyListener(keyListener);
        addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent e){
                keyListener.process(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Space War");
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public void paint(Graphics g){
        drawing.draw(g, getWidth(), getHeight());
    }

    public void setDrawing(IDrawing drawing) {
        this.drawing = drawing;
    }

    public void setKeyListener(IKeyListener keyListener) {
        this.keyListener = keyListener;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}