package com.visual.window;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.objects.LocalizableObject;
import com.objects.Planet;
import com.objects.Race;
import com.objects.ships.SpaceShip;
import java.awt.event.*;

/**
 *
 * @author Sergey
 */
public class StatisticForm extends javax.swing.JFrame {

    Race race1;
    Race race2;
    javax.swing.Timer timer;
    
    /**
     * Creates new form StatisticForm
     */
    public StatisticForm(Race _race1, Race _race2) {
        initComponents();
        race1 = _race1;
        race2 = _race2;
        timer = new javax.swing.Timer(200, new ActionListener(){
            public void actionPerformed(ActionEvent e){
                race1TextPane.setText(raceInformation(race1));
                race2TextPane.setText(raceInformation(race2));
            }
        });
        timer.start();
    }
    
    public String raceInformation(Race race){
        String text = "";
        for(Planet i: race.getPlanets())
        if(i.getPlayerColor() == race1.getPlayerColor())
                text += i.toString() + " "
                        + "(" + Integer.toString(i.location.X) + "," + Integer.toString(i.location.Y) + ") "
                        + Integer.toString(i.getResources()) + "\n";
        for(LocalizableObject i: race.getShips())
            text += i.toString() + " "
                    + "(" + Integer.toString(i.location.X) + "," + Integer.toString(i.location.Y) + ") "
                    + Integer.toString(((SpaceShip)i).getArmor()) + '\n';
        return text;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        race1TextPane1 = new javax.swing.JScrollPane();
        race1TextPane = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        race2TextPane = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistic");
        setResizable(false);

        jLabel1.setText("Race1");

        race1TextPane.setEditable(false);
        race1TextPane1.setViewportView(race1TextPane);

        race2TextPane.setEditable(false);
        jScrollPane1.setViewportView(race2TextPane);

        jLabel2.setText("Race2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(race1TextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 258, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(race1TextPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane race1TextPane;
    private javax.swing.JScrollPane race1TextPane1;
    private javax.swing.JTextPane race2TextPane;
    // End of variables declaration//GEN-END:variables
}
